### ISSUE TITLE
Clarify the license to make translation smoothly without consideration of copyrights

### ISSUE THREAD

**Issue by aquahika** [RoboCupJuniorTC/soccer-rules#57]
### Please describe your suggestion in one or two sentences

*Clarify the license to translate smoothly to local language.*

### Please explain why do you think it should be in the rules

Suggestion is CC-BY-SA -- Creative Commons Attribution + ShareAlike. 
https://en.wikipedia.org/wiki/Creative_Commons_license
![Screen Shot 2021-07-01 at 21 48 56](https://user-images.githubusercontent.com/2618822/124126951-25eb1b00-dab6-11eb-82a7-1dfa0e20f819.png)

The reason why I choose Creative-Commons here is it's commonly used in documents and they easily find the meaning in their language I guess, but feel free to suggest any type of licenses as you recommend for the rule book!

**Comment by mrshu** [comment]
Hey @aquahika , CC-BY-SA makes a lot of sense to me!

Feel free to add a PR that would add such a license to the repository. Furthermore, I think we can make it easier for others to actually translate the rules by making it obvious what it takes to set up a repository like this. Or even better, by keeping the translations here and providing infrastructure for making them easy to track long-term. I guess that's for another issue/pull request to discuss in full :slightly_smiling_face:
